### ISSUE TITLE
Failure to handle MenuEvents.MenuClosed

### ISSUE THREAD

**Issue by posixbofh** [isaacs-dev/Minidew-Mods#1]
This error repeats in SMAPI console when opening/closing the in-game menu with the latest version of FriendsForever (1.1.0) installed:

> 
> [SMAPI] A mod failed handling the MenuEvents.MenuClosed event:
> System.MissingMethodException: Method not found: 'Microsoft.Xna.Framework.Vector2 Microsoft.Xna.Framework.Point.ToVector2()'.
>    at IsaacS.FriendsForever.ModEntry.MenuClosed(Object sender, EventArgsClickableMenuClosed e)
>    at StardewModdingAPI.Framework.InternalExtensions.SafelyRaiseGenericEvent[TEventArgs](IMonitor monitor, String name, IEnumerable`1 handlers, Object sender, TEventArgs args) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\InternalExtensions.cs:line 65

**Comment by isaacs-dev** [comment]
Currently investigating. What SMAPI version and which menu?

**Comment by isaacs-dev** [comment]
This appears to be a Windows-specific issue with a pretty simple fix. I'll be releasing an update soon.
